# Generated by Django 5.0.3 on 2024-04-18 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='funkos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funko_api.funko'),
        ),
    ]
