# Generated by Django 5.0.3 on 2024-04-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0002_alter_user_funkos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='funkos',
        ),
        migrations.AddField(
            model_name='user',
            name='funkos',
            field=models.ManyToManyField(blank=True, to='funko_api.funko'),
        ),
    ]
