# Generated by Django 5.0.3 on 2024-04-25 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0003_remove_user_funkos_user_funkos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funko',
            old_name='numero',
            new_name='number',
        ),
    ]
