# Generated by Django 5.0.3 on 2024-06-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('float', models.IntegerField()),
                ('rarity', models.CharField(max_length=128)),
                ('pattern', models.IntegerField(default=0)),
            ],
        ),
    ]
