# Generated by Django 5.0.3 on 2024-06-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skins_cs2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skin',
            new_name='Skins',
        ),
    ]
